### ISSUE TITLE
Assertion types are unintuitive

### ISSUE THREAD

**Issue by ArtskydJ** [speckjs/speckjs#155]
The [`assertion types`](https://github.com/speckjs/speckjs#supported-assertion-types) are `==`, `===`, `!==`, and `!===`. JS devs are used to `==`, `===`, `!=`, and `!==`.

This violates the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

Is there a good reason for these non-standard assertions?

**Comment by nickbalestra** [comment]
Hey @ArtskydJ 
Thanks for bringing this up.

we discussed this for a while within the team.
Cause those assertions are used for equal and deep equal we didn't want to mix it up with the strict equal or equal operator found in js (this last one relate to coercion and not deep equality). 

I believe that Mixing those will violates way more the principle of least astonishment imho.
Hope this answer your question.

**Comment by ArtskydJ** [comment]
Whoops, I was mistaken. I thought it was doing a strict comparison, not a deep comparison.

It seems a bit weird how the assertion types are nearly identical to JS, when they perform a radically different function.
But now I'm bikeshedding. :smile:
