### ISSUE TITLE
Parse comments from source file

### ISSUE THREAD

**Issue by lsavage92** [speckjs/speckjs#3]

**Comment by nickbalestra** [comment]
I've experimented with few parsers, mainly esprima and acorn. Both have similar performances, but the later has a slightly better API. 
Acorn for what concern parsing comments, allows to run a function on all the component of each comments as they are parsed, this will allow for validation/formatting on the fly through some helpers.

As we will deal with a returned AST from the parser we will need some functional love to play with all those data, I suggest we may go with lodash or Ramda (lodash-fp could be a nice in between choice). Thoughts?

**Comment by lsavage92** [comment]
It sounds like Acorn will be the most efficient way of doing what we need, but I'll have to look more in depth at the API to see.

**Comment by nickbalestra** [comment]
My idea is to move that parsing logic of acorn + comment cb fn() out of speck.js into /parsing as a 'standalone' module so that it can just work agnostically:
input: file/string/blog
output: rawParsed speckjs comments 

that raw output data can be extracted out of them on as in #4 being its input
