### ISSUE TITLE
Convert parsed comments into usable format

### ISSUE THREAD

**Issue by lsavage92** [speckjs/speckjs#4]

**Comment by nickbalestra** [comment]
As we will deal with a returned AST from the parser we will need some functional love to play with all those data, I suggest we may go with lodash or Ramda (lodash-fp could be a nice in between choice). Thoughts?

**Comment by nickbalestra** [comment]
After digging tonight, some possibility emerged. It seems that instead of building our own pattern-matching / data extrication helper, we could play with some of the following and/or search for more:
- https://github.com/laktek/extract-values
- https://github.com/princejwesley/extractjs
