### ISSUE TITLE
create launch strategy for SpeckJS

### ISSUE THREAD

**Issue by gregRV** [speckjs/speckjs#98]

**Comment by gregRV** [comment]
Draft the post that will be used for Hacker News, Reddit, and various social media outlets

**Comment by lsavage92** [comment]
List I have so far of places we should post.

List of websites for exposure:
Hacker News - https://news.ycombinator.com/
Echo JS - http://www.echojs.com/

Subreddits:
Node - https://www.reddit.com/r/node
JavaScript - https://www.reddit.com/r/javascript
